### ISSUE TITLE
`Jl.eval('2+2')` throws `Function not found`

### ISSUE THREAD

**Issue by abhijithch** [twadleigh/jlcall#11] opened 2016-02-18 06:05 UTC
I am running MATLAB 2015b on windows 7 machine with the Microsoft Visual C++ 2012 compiler. The `Jlcall.mex64` is getting created without any problems. Also `Jl.check_init()` returns `1`. However upon calling `Jl.eval(2+2)` throws an `Function not found` error. We have checked that things work on OS X. Any help is appreciated. 

This works on `OS X`.

**Comment by twadleigh** [comment] 2016-02-19 19:39
Hmm, I just saw that you opened this. Don't know why I didn't see an e-mail for it. (I haven't been checking in to github very often lately.) I'll take a look when I have a moment in the next day or so.

Thanks for checking jlcall out and reporting the issue.

**Comment by twadleigh** [comment] 2016-02-20 15:58
Hmm. I'm not able to reproduce it. I'm running a slightly different setup (2015a with VS2013), but I doubt that would be an issue. The `Function not found` error, is that a julia error?

**Comment by abhijithch** [comment] 2016-02-21 07:34
No this is the C++ error from [this](https://github.com/twadleigh/jlcall/blob/master/src/jlcall.cpp#L41) line. I suspect something wrong in my environment, thanks for confirming this works with windows setup.

**Comment by twadleigh** [comment] 2016-02-21 15:27
OK, I suspect this results from some failure during initialization when trying to load the `boot.jl` script. One cause of that would be not having the `MATLAB.jl` package for the version of julia `jlcall` is using.

**Comment by twadleigh** [comment] 2016-11-05 23:14
Closing this. Open new issues as you find them.

**Closed as completed by twadleigh** 2016-11-05 23:14 UTC
